var events = [
{
"Title": "FHE Fun",
"Description": "Be spiritual at FHE",
"StartTime": "19:00:00",
"EndTime": "20:00:00",
"Date": "2015-04-06",
"Price": "3.00",
"Picture": "img/spiritual.svg",
"Location": "Your FHE Place",
"Email": null},
{
"Title": "Enjoy Choir",
"Description": "Listen to choir performance on the big screen",
"StartTime": "09:00:00",
"EndTime": "11:00:00",
"Date": "2015-04-06",
"Price": "5.00",
"Picture": "img/performance.svg",
"Location": "Crossroads",
"Email": null},
{
"Title": "Swimming",
"Description": "Fun swimming activity for fitness",
"StartTime": "19:00:00",
"EndTime": "20:00:00",
"Date": "2015-04-07",
"Price": "0.00",
"Picture": "img/fitness.svg",
"Location": "Hart",
"Email": null},
{
"Title": "Mic Night",
"Description": "Comedy and fun",
"StartTime": "17:00:00",
"EndTime": "18:00:00",
"Date": "2015-04-07",
"Price": "1.00",
"Picture": "img/comedy.svg",
"Location": "MC Little Theatre",
"Email": null},
{
"Title": "Bonfire and camp",
"Description": "Camping in the outdoors with a fun bonfire for you and your friends",
"StartTime": "20:00:00",
"EndTime": "23:00:00",
"Date": "2015-04-07",
"Price": "3.00",
"Picture": "img/outdoors.svg",
"Location": "null",
"Email": null},
{
"Title": "Game night",
"Description": "Be social and chat with people like you",
"StartTime": "10:00:00",
"EndTime": "12:00:00",
"Date": "2015-04-08",
"Price": "0.00",
"Picture": "img/social.svg",
"Location": "MC Ballroom",
"Email": null},
{
"Title": "Learn Message",
"Description": "Receive instruction to give messages",
"StartTime": "11:00:00",
"EndTime": "12:00:00",
"Date": "2015-04-08",
"Price": "2.00",
"Picture": "img/instruction.svg",
"Location": "Taylor Cultural Hall",
"Email": null},
{
"Title": "The Swimming Party",
"Description": "Play around and swimming a lot",
"StartTime": "05:00:00",
"EndTime": "07:30:00",
"Date": "2015-04-08",
"Price": "5.00",
"Picture": "img/dance.svg",
"Location": "The swimming pool at the hart",
"Email": null},
{
"Title": "Sing Along with Disney Music",
"Description": "If you know some disney music or some music that is inspiring,  come and join us to sign with your voice",
"StartTime": "08:00:00",
"EndTime": "10:00:00",
"Date": "2015-04-08",
"Price": "0.00",
"Picture": "img/performance.svg",
"Location": "The Ivy Apartments",
"Email": null},
];